bwalsh0 commented on 24 Apr 2019
System information
Have I written custom code (as opposed to using example directory): No, using keras/datasets/imdb.py
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 b1803
TensorFlow backend (yes / no): yes
TensorFlow version: 1.13.1
Keras version: 2.2.4 (using keras from tensorflow)
Python version: 3.7.3
CUDA/cuDNN version: 10.0
GPU model and memory: NVIDIA GTX 960M 2GB
Describe the current behavior
ValueError: Object arrays cannot be loaded when allow_pickle=False
Describe the expected behavior
np.load(path) should be updated to np.load(path, allow_pickle)
Code to reproduce the issue
Line 86 at keras/datasets/imdb.py,
with np.load(path, allow_pickle=True) as f:
    x_train, labels_train = f['x_train'], f['y_train']
    x_test, labels_test = f['x_test'], f['y_test']
Other info / logs
numpy\lib\npyio.py", line 262, in __getitem__ pickle_kwargs=self.pickle_kwargs)
numpy\lib\format.py", line 692, in read_array raise ValueError("Object arrays cannot be loaded when " ValueError: Object arrays cannot be loaded when allow_pickle=False
5